# Generated by Django 3.1.1 on 2020-09-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('former_url', models.CharField(max_length=255)),
                ('new_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
